version: 2
py36: &py36
  working_directory: ~/code
  docker:
    - image: circleci/python:3.6
      environment:
        RELEASE_MATCH: "release/*"

py37: &py37
  working_directory: ~/code
  docker:
    - image: circleci/python:3.7
      environment:
        RELEASE_MATCH: "release/*"

jobs:
  lint:
    <<: *py36
    steps:
      - checkout
      - run:
          name: lint checks
          command: |
            export PATH=$PATH:/home/circleci/.local/bin
            pip install -r src/requirements/install.pip --user
            pip install -r src/requirements/testing.pip --user
            flake8 src/
            isort -rc src/ --check-only

  test-py36-d20:
    <<: *py36
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            pip install "django>=2.0,<2.1" --user
            ./test.sh

  test-py36-d21:
    <<: *py36
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            pip install "django>=2.1,<2.2" --user
            ./test.sh

  test-py36-d22:
    <<: *py36
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            pip install "django>=2.2,<2.3" --user
            ./test.sh

  test-py37-d20:
    <<: *py37
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            pip install "django>=2.0,<2.1" --user
            ./test.sh

  test-py37-d21:
    <<: *py37
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            pip install "django>=2.1,<2.2" --user
            ./test.sh

  test-py37-d22:
    <<: *py37
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            pip install "django>=2.2,<2.3" --user
            ./test.sh

  tag:
    docker:
      - image: circleci/python:3.6
        environment:
          API_URL: https://api.github.com/repos/unicef/unicef-djangolib
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "bc:ec:f3:95:b8:21:dd:1a:a9:78:0b:1e:58:b8:bd:9e"
      - run:
          name: package and release
          command: |
            export PATH=/home/circleci/.local/bin:$PATH
            export TAG=${TAG:=${CIRCLE_BRANCH#*/}}
            export CIRCLE_TAG=${TAG}
            python setup.py verify

            git status
            git reset --hard

            git config user.email "ci@unicef.org"
            git config user.name "CI"

            git checkout master
            git merge --no-ff release/$TAG -m "merge release/$TAG"
            git tag -a -m "v$TAG" $TAG
            git checkout develop
            git merge --no-ff release/$TAG -m "merge release/$TAG"
            git push --verbose --tags
            git push origin --verbose --delete release/$TAG
      - run:
          name: init .pypirc
          command: |
            echo -e "[distutils]" >> ~/.pypirc
            echo -e "index-servers =" >> ~/.pypirc
            echo -e "    pypi" >> ~/.pypirc
            echo -e "" >> ~/.pypirc
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username: $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password: $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: release
          command: |
            export TAG=${TAG:=${CIRCLE_BRANCH#*/}}
            export TODAY=`date '+%d %B %Y at %H:%M'`
            function is_pre()
            {
                [[ "$(echo "$TAG" | sed 's/[0-9.]//g')" == "" ]] && echo false || echo true
            }
            function data() {
            cat <<EOF
            { "tag_name": "$TAG",
              "name": "v$TAG",
              "body": "version $TAG - Built on $TODAY",
              "draft": false,
              "prerelease": $(is_pre)
            }
            EOF
            }
            data=$(data)
            curl -X POST -s \
              --fail --verbose \
              -H "Accept: application/json" \
              -H "Content-Type:application/json" \
              -H "Authorization: token ${GITHUB_TOKEN}" \
              ${API_URL}/releases \
              -d "$data"

            git checkout $TAG
            pip install twine --user
            twine upload dist/*

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test-py36-d20:
          requires:
            - lint
      - test-py36-d21:
          requires:
            - lint
      - test-py36-d22:
          requires:
            - lint
      - test-py37-d20:
          requires:
            - lint
      - test-py37-d21:
          requires:
            - lint
      - test-py37-d22:
          requires:
            - lint
      - tag:
          requires:
            - test-py36-d20
            - test-py36-d21
            - test-py36-d22
            - test-py37-d20
            - test-py37-d21
            - test-py37-d22
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
